# Generated by Django 5.0.6 on 2025-01-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('empid', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('phonenumber', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
