# Generated by Django 5.0.6 on 2025-01-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_data',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
