# Generated by Django 5.0.6 on 2024-12-27 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Dept', models.CharField(max_length=100)),
                ('Empid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('phonenumber', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=20)),
                ('domain', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=10, unique=True)),
                ('guardiannumber', models.CharField(max_length=10)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.employeedata')),
            ],
        ),
    ]
