# Generated by Django 5.0.6 on 2024-12-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=255),
        ),
    ]
