# Generated by Django 5.0.6 on 2024-12-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentdata_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='hub',
            field=models.CharField(choices=[('BCK', 'Calicut'), ('BCE', 'Kochi'), ('BCT', 'Thiruvananthapuram'), ('BCB', 'Bangalore'), ('BCR', 'Remote'), ('BCCO', 'Coimbatore'), ('BCCH', 'Chennai')], default='test', max_length=6),
        ),
    ]
