# Generated by Django 5.0.6 on 2024-12-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentdata_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedata',
            name='Designation',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
