# Generated by Django 5.0.6 on 2025-01-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_employeedata_work_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='Designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Work_location',
            field=models.CharField(max_length=50),
        ),
    ]
