# Generated by Django 5.0.6 on 2025-01-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_studentdata_guardianname'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedata',
            name='email',
            field=models.EmailField(default='test', max_length=255),
        ),
    ]
